{{- if .Values.serviceAccount.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-role
  labels:
    {{- include "chart.labels" . | nindent 4 }}
rules:
{{- with .Values.serviceAccount.rbac.rules }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}