apiVersion: v1
kind: PersistentVolume
metadata:
    name: tts-sst-volume
    labels:
        type: local
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    storageClassName: local-path
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: "/code/files"