apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: tts-stt-pvc
    namespace: tts-stt-svc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: local-path