repositories:
  - name: kubeai
    url: https://www.kubeai.org
  - name: k8sgpt
    url: https://charts.k8sgpt.ai
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: kubeai
    namespace: kubeai
    chart: kubeai/kubeai
    version: 0.19.0
    set:
      - name: secrets.huggingface.token
        value: {{ requiredEnv "HUGGINGFACE_TOKEN" }}
  - name: k8sgpt-operator
    namespace: k8sgpt-operator-system
    chart: k8sgpt/k8sgpt-operator
    version: 0.2.14
  - name: argocd
    namespace: argocd
    chart: argo/argo-cd
    version: 5.41.0
  # - name: controller
  #   namespace: tournesol
  #   chart: ./tournesol/controller/chart
  - name: gh-service
    namespace: tournesol
    chart: ./tournesol/gh/chart
    values:
      - values.yaml
  - name: tts-stt
    namespace: tournesol
    chart: ./tournesol/tts-stt/chart
    values:
      - values.yaml
  - name: discordbot
    namespace: tournesol
    chart: ./tournesol/discord_bot/chart
    values:
      - values.yaml
