apiVersion: apps/v1
kind: Deployment
metadata:
  name: prof-tournesol-controller
  namespace: k8sgpt-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prof-tournesol-controller
  template:
    metadata:
      labels:
        app: prof-tournesol-controller
    spec:
      serviceAccountName: prof-tournesol-controller-sa
      containers:
        - name: controller
          image: result-controller:latest # Use the local image name
          imagePullPolicy: IfNotPresent # Changed to IfNotPresent
          env:
            - name: GITHUB_OWNER
              value: "mfernd"
            - name: GITHUB_REPO
              value: "prof-tournesol"
            - name: GITHUB_BRANCH
              value: "main"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prof-tournesol-controller-sa
  namespace: k8sgpt-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prof-tournesol-controller-role
rules:
  - apiGroups: ["core.k8sgpt.ai"]
    resources: ["results"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["configmaps", "pods", "secrets", "services", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "statefulsets", "replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prof-tournesol-controller-rolebinding
subjects:
  - kind: ServiceAccount
    name: prof-tournesol-controller-sa
    namespace: k8sgpt-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prof-tournesol-controller-role
