# App will be marked as "healthy" but will spit out logs about not being able to start (workers keep getting killed off)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-unstable
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true

  destination:
    namespace: apps-nginx-unstable
    server: https://kubernetes.default.svc

  source:
    repoURL: https://github.com/mfernd/prof-tournesol.git
    path: apps/nginx-unstable
    targetRevision: HEAD
