# Postgres that will OOM and enter a crashloop backoff

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-oom
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true

  destination:
    namespace: apps-postgres-oom
    server: https://kubernetes.default.svc

  source:
    path: ''
    repoURL: registry-1.docker.io/bitnamicharts
    chart: 'postgresql'
    targetRevision: '16.4.5'
    helm:
      valuesObject:
        primary:
          resources:
            requests:
              cpu: "0.2"
              memory: "6Mi"
            limits:
              cpu: "0.3"
              memory: "8Mi"
