apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-oom
spec:
  # Project
  project: gaia-support
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true

  # Namespace
  destination:
    namespace: apps-postgres-oom
    server: https://kubernetes.default.svc

  source:
    path: ''
    repoURL: registry-1.docker.io/bitnamicharts
    chart: 'postgresql'
    targetRevision: '16.4.5'
    helm:
      valuesObject:
        primary:
          resourcesPreset: "nano"
