# HOF - Higher Order Function
#  This application will deploy other apps in the manifests/apps/ folder
# --
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-manager
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true

  destination:
    namespace: argocd
    server: https://kubernetes.default.svc

  source:
    repoURL: https://github.com/mfernd/prof-tournesol.git
    path: manifests/apps/
    targetRevision: HEAD
