# HOF - Higher Order Function
#  This ApplicationSet will generate one Application per folder in apps/
#  Each app will be deployed in its own namespace matching the folder name
# --
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-manager
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/mfernd/prof-tournesol.git
        revision: HEAD
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
      destination:
        namespace: '{{path.basename}}'
        server: https://kubernetes.default.svc
      source:
        repoURL: https://github.com/mfernd/prof-tournesol.git
        path: '{{path}}'
        targetRevision: HEAD