apiVersion: apps/v1
kind: Deployment
metadata:
  name: invalid-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fail-app
  template:
    metadata:
      labels:
        app: fail-app
    spec:
      containers:
      - name: fail-container
        image: busybox
        command: ["sh", "-c", "exit 1"]
