apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-local
  namespace: k8sgpt-operator-system
spec:
  ai:
    model: gemma3-1b-cpu
    backend: localai
    baseUrl: http://kubeai.kubeai.svc.cluster.local:80/openai/v1
    enabled: true
  filters:
    - Pod
    - Deployment
  version: v0.4.13
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8sgpt-list-configmaps
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8sgpt-list-configmaps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8sgpt-list-configmaps
subjects:
  - kind: ServiceAccount
    name: k8sgpt-k8sgpt-operator-system
    namespace: k8sgpt-operator-system
