apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}
type: Opaque
data:
  githubAppId: {{ .Values.gh.githubAppId | b64enc | quote }}
  githubAppPrivateKey: {{ .Values.gh.githubAppPrivateKey | b64enc | quote }}
