name: Build and Push `gh` Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the image'
        required: true
        type: string

jobs:
  build_and_push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/reusable-docker.yaml
    with:
      path: ./tournesol/gh
      image: ghcr.io/${{ github.repository }}/gh
      version: ${{ github.event.inputs.version }}
