name: Build and Push `tts-stt` Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the image (ex: 0.1.0)'
        type: string

jobs:
  build_and_push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/reusable-docker.yaml
    with:
      path: ./tournesol/tts-stt
      image: ghcr.io/${{ github.repository }}/tts-stt
      version: ${{ github.event.inputs.version }}
